import { Pipe, PipeTransform, SecurityContext, inject } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

/**
 * @generatedInfoDoc
 * InfoDoc: class `SafeHtmlPipe` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `SafeHtmlPipe` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `SafeHtmlPipe` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `SafeHtmlPipe` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */



@Pipe({
  name: 'safeHtml',
  standalone: true
})
export class SafeHtmlPipe implements PipeTransform {
  private readonly sanitizer = inject(DomSanitizer);

    /**
 * @generatedInfoDoc
 * InfoDoc: method `SafeHtmlPipe`.`transform()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `SafeHtmlPipe`.`transform()` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `SafeHtmlPipe`.`transform()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `SafeHtmlPipe`.`transform()` participates in the `SafeHtmlPipe` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `SafeHtmlPipe`.`transform()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `SafeHtmlPipe`.`transform()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `SafeHtmlPipe`.`transform()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */



public transform(value: string | null | undefined): string {
    return this.sanitizer.sanitize(SecurityContext.HTML, value ?? '') ?? '';
  }
}
