import { Pipe, PipeTransform, inject } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

/**
 * @generatedInfoDoc
 * InfoDoc: class `SafeHtmlPipe` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `SafeHtmlPipe` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `SafeHtmlPipe` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `SafeHtmlPipe` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 14: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 15: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 16: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 17: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 18: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 19: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 20: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 21: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 22: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 23: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 24: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 25: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 26: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 27: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 28: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 29: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 30: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 31: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 32: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 33: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 34: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 35: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 36: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 37: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 38: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 39: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 40: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 41: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 42: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 43: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 44: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 45: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 46: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 47: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 48: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 49: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 50: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 51: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 52: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 53: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 54: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 55: class `SafeHtmlPipe` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 56: class `SafeHtmlPipe` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 57: class `SafeHtmlPipe` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 58: class `SafeHtmlPipe` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 */




@Pipe({
  name: 'safeHtml',
  standalone: true
})
export class SafeHtmlPipe implements PipeTransform {
  private readonly sanitizer = inject(DomSanitizer);

    /**
 * @generatedInfoDoc
 * InfoDoc: method `SafeHtmlPipe`.`transform()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `SafeHtmlPipe`.`transform()` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `SafeHtmlPipe`.`transform()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `SafeHtmlPipe`.`transform()` participates in the `SafeHtmlPipe` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `SafeHtmlPipe`.`transform()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `SafeHtmlPipe`.`transform()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `SafeHtmlPipe`.`transform()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */




public transform(value: string | null | undefined): SafeHtml {
    const safeHtml = this.sanitizeEditorHtml(value ?? '');
    return this.sanitizer.bypassSecurityTrustHtml(safeHtml);
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `SafeHtmlPipe`.`sanitizeEditorHtml()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `SafeHtmlPipe`.`sanitizeEditorHtml()` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `SafeHtmlPipe`.`sanitizeEditorHtml()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `SafeHtmlPipe`.`sanitizeEditorHtml()` participates in the `SafeHtmlPipe` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `SafeHtmlPipe`.`sanitizeEditorHtml()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `SafeHtmlPipe`.`sanitizeEditorHtml()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `SafeHtmlPipe`.`sanitizeEditorHtml()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 05: method `SafeHtmlPipe`.`sanitizeEditorHtml()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 06: method `SafeHtmlPipe`.`sanitizeEditorHtml()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 07: method `SafeHtmlPipe`.`sanitizeEditorHtml()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 08: method `SafeHtmlPipe`.`sanitizeEditorHtml()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 09: method `SafeHtmlPipe`.`sanitizeEditorHtml()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 10: method `SafeHtmlPipe`.`sanitizeEditorHtml()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 11: method `SafeHtmlPipe`.`sanitizeEditorHtml()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 12: method `SafeHtmlPipe`.`sanitizeEditorHtml()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 13: method `SafeHtmlPipe`.`sanitizeEditorHtml()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 14: method `SafeHtmlPipe`.`sanitizeEditorHtml()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 15: method `SafeHtmlPipe`.`sanitizeEditorHtml()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 16: method `SafeHtmlPipe`.`sanitizeEditorHtml()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 17: method `SafeHtmlPipe`.`sanitizeEditorHtml()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 18: method `SafeHtmlPipe`.`sanitizeEditorHtml()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 19: method `SafeHtmlPipe`.`sanitizeEditorHtml()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   */
private sanitizeEditorHtml(html: string): string {
    const template = document.createElement('template');
    template.innerHTML = html;

    template.content
      .querySelectorAll('meta, script, iframe, embed, object, link, style')
      .forEach(element => { element.remove(); });

    template.content.querySelectorAll('*').forEach(element => {
      Array.from(element.attributes).forEach(attribute => {
        const name = attribute.name.toLowerCase();
        const value = attribute.value.trim().toLowerCase();

        if (
          name.startsWith('on') ||
          name === 'srcdoc' ||
          this.isUnsafeUrlAttribute(name, value, element)
        ) {
          element.removeAttribute(attribute.name);
        }
      });

      this.sanitizeStyleAttribute(element as HTMLElement);
    });

    return template.innerHTML;
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` participates in the `SafeHtmlPipe` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 05: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 06: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 07: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 08: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 09: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 10: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 11: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 12: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 13: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 14: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 15: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 16: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 17: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 18: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 19: method `SafeHtmlPipe`.`sanitizeStyleAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   */
private sanitizeStyleAttribute(element: HTMLElement): void {
    const style = element.getAttribute('style');
    if (style === null) {
      return;
    }

    if (style.trim() === '') {
      element.removeAttribute('style');
      return;
    }

    const sanitizedDeclarations = Array.from(element.style)
      .map(propertyName => {
        const value = element.style.getPropertyValue(propertyName).trim();
        const priority = element.style.getPropertyPriority(propertyName);

        if (this.isUnsafeStyleValue(value)) {
          return '';
        }

        return `${propertyName}: ${value}${priority ? ` !${priority}` : ''}`;
      })
      .filter(Boolean);

    if (sanitizedDeclarations.length === 0) {
      element.removeAttribute('style');
      return;
    }

    element.setAttribute('style', `${sanitizedDeclarations.join('; ')};`);
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `SafeHtmlPipe`.`isUnsafeStyleValue()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `SafeHtmlPipe`.`isUnsafeStyleValue()` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `SafeHtmlPipe`.`isUnsafeStyleValue()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `SafeHtmlPipe`.`isUnsafeStyleValue()` participates in the `SafeHtmlPipe` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `SafeHtmlPipe`.`isUnsafeStyleValue()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `SafeHtmlPipe`.`isUnsafeStyleValue()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `SafeHtmlPipe`.`isUnsafeStyleValue()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
private isUnsafeStyleValue(value: string): boolean {
    const normalizedValue = value.replace(/\s+/g, '').toLowerCase();

    return normalizedValue.includes('javascript:') ||
      normalizedValue.includes('expression(') ||
      normalizedValue.includes('url(');
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` is implemented in `projects/lib-magnetar-quill/src/lib/pipes/safe-html.pipe.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` participates in the `SafeHtmlPipe` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 05: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   * Why 06: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 07: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 08: method `SafeHtmlPipe`.`isUnsafeUrlAttribute()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
private isUnsafeUrlAttribute(name: string, value: string, element: Element): boolean {
    if (!['href', 'src', 'action', 'formaction'].includes(name)) {
      return false;
    }

    const normalizedValue = Array.from(value)
      .filter(character => character.charCodeAt(0) > 32)
      .join('')
      .toLowerCase();
    if (normalizedValue.startsWith('javascript:') || normalizedValue.startsWith('vbscript:')) {
      return true;
    }

    const isImageDataUrl = element.tagName.toLowerCase() === 'img' &&
      normalizedValue.startsWith('data:image/');

    return normalizedValue.startsWith('data:') && !isImageDataUrl;
  }
}
