/**
 * @generatedInfoDoc
 * InfoDoc: class `ImageModalComponentModel` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `ImageModalComponentModel` is implemented in `projects/lib-magnetar-quill/src/lib/models/image-modal-component-model.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `ImageModalComponentModel` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `ImageModalComponentModel` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/models/image-modal-component-model.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `ImageModalComponentModel` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `ImageModalComponentModel` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `ImageModalComponentModel` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `ImageModalComponentModel` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `ImageModalComponentModel` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `ImageModalComponentModel` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `ImageModalComponentModel` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */


export class ImageModalComponentModel {
  public url: string = '';
  public alt: string = '';
  public width: number | null = null;
  public height: number | null = null;
  public border: number = 0;
  public hPadding: number = 0;
  public vPadding: number = 0;
  public alignment: 'start' | 'end' | 'left' | 'right' | 'center' | 'justify' | 'stretch' | 'justify-all' = 'left';
}
