import { Injectable } from '@angular/core';
import {ImageInternalData} from "../models/image-internal-data";
import {BehaviorSubject} from "rxjs";

/**
 * @generatedInfoDoc
 * InfoDoc: class `ContentService` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `ContentService` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `ContentService` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `ContentService` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/services/content.service.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 14: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 15: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 16: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 17: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 18: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 19: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 20: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 21: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 22: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 23: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 24: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 25: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 26: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 27: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 28: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 29: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 30: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 31: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 32: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 33: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 34: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 35: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 36: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 37: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 38: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 39: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 40: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 41: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 42: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 43: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 44: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 45: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 46: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 47: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 48: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 49: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 50: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 51: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 52: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 53: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 54: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 55: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 56: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 57: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 58: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 59: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 60: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 61: class `ContentService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 62: class `ContentService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 63: class `ContentService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 64: class `ContentService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */





@Injectable()
export class ContentService {


  // Observable to track the HTML content of the editor
  private editorContent = new BehaviorSubject<string>('');
  editorContent$ = this.editorContent.asObservable();

  // Method to update the content
    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`setEditorContent()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`setEditorContent()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`setEditorContent()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`setEditorContent()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`setEditorContent()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`setEditorContent()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`setEditorContent()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */





public setEditorContent(htmlContent: string): void {
    this.editorContent.next(htmlContent);
  }

  // Method to retrieve the current content as a snapshot
    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`getEditorContent()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`getEditorContent()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`getEditorContent()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`getEditorContent()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`getEditorContent()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`getEditorContent()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`getEditorContent()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */





public getEditorContent(): string {
    return this.editorContent.getValue();
  }

  // Method to insert an image
  // Method to insert image as HTML content
    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`insertImage()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`insertImage()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`insertImage()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`insertImage()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`insertImage()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`insertImage()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`insertImage()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ContentService`.`insertImage()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 */





public insertImage(imageData: { url: string, alt?: string, width?: number, height?: number }): void {
    const imageHtml = `<img src="${imageData.url}" alt="${imageData.alt || ''}"
                        width="${imageData.width || ''}" height="${imageData.height || ''}" />`;

    // Assuming content appending, you can customize this as needed
    const currentContent = this.getEditorContent();
    const updatedContent = currentContent + imageHtml;
    this.setEditorContent(updatedContent);
  }


    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`insertHtmlAtCursor()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`insertHtmlAtCursor()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`insertHtmlAtCursor()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`insertHtmlAtCursor()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`insertHtmlAtCursor()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`insertHtmlAtCursor()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`insertHtmlAtCursor()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ContentService`.`insertHtmlAtCursor()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: method `ContentService`.`insertHtmlAtCursor()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: method `ContentService`.`insertHtmlAtCursor()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: method `ContentService`.`insertHtmlAtCursor()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: method `ContentService`.`insertHtmlAtCursor()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: method `ContentService`.`insertHtmlAtCursor()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: method `ContentService`.`insertHtmlAtCursor()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: method `ContentService`.`insertHtmlAtCursor()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */





public insertHtmlAtCursor(html: string): void {
    const selection = window.getSelection();
    if (selection && selection.rangeCount > 0) {
      const range = selection.getRangeAt(0);
      const fragment = document.createRange().createContextualFragment(html);
      const lastInsertedNode = fragment.lastChild;
      range.deleteContents(); // Remove the current selection
      range.insertNode(fragment); // Insert the HTML fragment

      if (lastInsertedNode) {
        range.setStartAfter(lastInsertedNode);
        range.collapse(true);
        selection.removeAllRanges();
        selection.addRange(range);
      }
    }
  }

    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`insertTextAtCursor()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`insertTextAtCursor()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`insertTextAtCursor()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`insertTextAtCursor()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`insertTextAtCursor()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`insertTextAtCursor()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`insertTextAtCursor()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ContentService`.`insertTextAtCursor()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: method `ContentService`.`insertTextAtCursor()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: method `ContentService`.`insertTextAtCursor()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: method `ContentService`.`insertTextAtCursor()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: method `ContentService`.`insertTextAtCursor()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: method `ContentService`.`insertTextAtCursor()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 */





public insertTextAtCursor(text: string): void {
    const selection = window.getSelection();
    if (!selection || selection.rangeCount === 0) return;

    const range = selection.getRangeAt(0);
    range.deleteContents();
    const textNode = document.createTextNode(text);
    range.insertNode(textNode);

    // Move the cursor after the inserted text
    range.setStartAfter(textNode);
    range.collapse(true);
    selection.removeAllRanges();
    selection.addRange(range);
  }

    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`insertImageFromUrl()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`insertImageFromUrl()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`insertImageFromUrl()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`insertImageFromUrl()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`insertImageFromUrl()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`insertImageFromUrl()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`insertImageFromUrl()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ContentService`.`insertImageFromUrl()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: method `ContentService`.`insertImageFromUrl()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: method `ContentService`.`insertImageFromUrl()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: method `ContentService`.`insertImageFromUrl()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: method `ContentService`.`insertImageFromUrl()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: method `ContentService`.`insertImageFromUrl()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: method `ContentService`.`insertImageFromUrl()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: method `ContentService`.`insertImageFromUrl()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: method `ContentService`.`insertImageFromUrl()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 */





public insertImageFromUrl(imageData: ImageInternalData): void {
    const img = document.createElement('img');
    img.src = imageData.url;
    img.alt = imageData.alt || '';
    img.style.width = imageData.width ? `${imageData.width}px` : 'auto';
    img.style.height = imageData.height ? `${imageData.height}px` : 'auto';
    img.style.borderWidth = `${imageData.border}px`;
    img.style.padding = `${imageData.vPadding}px ${imageData.hPadding}px`;
    img.style.textAlign = imageData.alignment ?? 'left';

    const selection = window.getSelection();
    if (selection && selection.rangeCount > 0) {
      const range = selection.getRangeAt(0);
      range.insertNode(img);
      range.collapse(false);
    }
  }


    /**
 * @generatedInfoDoc
 * InfoDoc: method `ContentService`.`getSelectedElements()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ContentService`.`getSelectedElements()` is implemented in `projects/lib-magnetar-quill/src/lib/services/content.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ContentService`.`getSelectedElements()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ContentService`.`getSelectedElements()` participates in the `ContentService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ContentService`.`getSelectedElements()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ContentService`.`getSelectedElements()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ContentService`.`getSelectedElements()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ContentService`.`getSelectedElements()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: method `ContentService`.`getSelectedElements()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: method `ContentService`.`getSelectedElements()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: method `ContentService`.`getSelectedElements()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: method `ContentService`.`getSelectedElements()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: method `ContentService`.`getSelectedElements()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: method `ContentService`.`getSelectedElements()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: method `ContentService`.`getSelectedElements()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: method `ContentService`.`getSelectedElements()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 */





public getSelectedElements(): HTMLElement[] {
    const selection = window.getSelection();
    const elements: HTMLElement[] = [];
    if (selection && !selection.isCollapsed) {
      const range = selection.getRangeAt(0);
      let container: Node = range.commonAncestorContainer;
      if (container.nodeType === Node.TEXT_NODE) {
        container = container.parentElement as HTMLElement;
      }
      if (container instanceof HTMLElement) {
        if (container.tagName === 'P') {
          elements.push(container);
        } else {
          container.querySelectorAll('p').forEach(paragraph => elements.push(paragraph));
        }
      }
    }
    return elements;
  }

}
