// File: keyboard-shortcut.service.ts
import { Injectable, OnDestroy, inject, ElementRef } from '@angular/core';
import { Subject } from 'rxjs';
import {FormattingService} from "./formatting.service";
import {SHORTCUTS} from "../models/shortcut-map";
import {ShortcutAction} from "../models/key-shortcuts";


// NOTE: filter, map from rxjs/operators were imported but not used in the original snippet. Removed for now.
// import { filter, map } from 'rxjs/operators';

// Import other services if needed (e.g., HistoryService for Undo/Redo)
// import { HistoryService } from './services/history.service';

/**
 * @generatedInfoDoc
 * InfoDoc: class `KeyboardShortcutService` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `KeyboardShortcutService` is implemented in `projects/lib-magnetar-quill/src/lib/services/keyboard-shortcut.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `KeyboardShortcutService` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `KeyboardShortcutService` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/services/keyboard-shortcut.service.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 14: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 15: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 16: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 17: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 18: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 19: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 20: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 21: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 22: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 23: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 24: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 25: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 26: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 27: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 28: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 29: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 30: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 31: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 32: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 33: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 34: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 35: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 36: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 37: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 38: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 39: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 40: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 41: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 42: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 43: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 44: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 45: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 46: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 47: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 48: class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 49: class `KeyboardShortcutService` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 50: class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 51: class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 */


@Injectable()
export class KeyboardShortcutService implements OnDestroy {

  private readonly destroy$ = new Subject<void>();
  private readonly fmt = inject(FormattingService);
  private editorElement: HTMLElement | null = null;
  // Example: Inject HistoryService if it handles Undo/Redo
  // private readonly history = inject(HistoryService);

    /**
 * @generatedInfoDoc
 * InfoDoc: constructor for class `KeyboardShortcutService` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: constructor for class `KeyboardShortcutService` is implemented in `projects/lib-magnetar-quill/src/lib/services/keyboard-shortcut.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: constructor for class `KeyboardShortcutService` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: constructor for class `KeyboardShortcutService` participates in the `KeyboardShortcutService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: constructor for class `KeyboardShortcutService` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: constructor for class `KeyboardShortcutService` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: constructor for class `KeyboardShortcutService` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */


constructor() {
    // Use capture phase (true) to catch event early, potentially overriding default browser behavior
    window.addEventListener('keydown', this.handleKeydown, true);
  }

  /**
   * Initializes the service with the host element of the editor.
   * This is used to scope keyboard shortcuts to a specific editor instance.
   * @param {HTMLElement} element - The editor's native element.
   */
    /**
 * @generatedInfoDoc
 * InfoDoc: method `KeyboardShortcutService`.`initialize()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `KeyboardShortcutService`.`initialize()` is implemented in `projects/lib-magnetar-quill/src/lib/services/keyboard-shortcut.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `KeyboardShortcutService`.`initialize()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `KeyboardShortcutService`.`initialize()` participates in the `KeyboardShortcutService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `KeyboardShortcutService`.`initialize()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `KeyboardShortcutService`.`initialize()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `KeyboardShortcutService`.`initialize()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */


public initialize(element: HTMLElement): void {
    this.editorElement = element;
  }

  /** remove listener when the service is destroyed */
    /**
 * @generatedInfoDoc
 * InfoDoc: method `KeyboardShortcutService`.`ngOnDestroy()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `KeyboardShortcutService`.`ngOnDestroy()` is implemented in `projects/lib-magnetar-quill/src/lib/services/keyboard-shortcut.service.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `KeyboardShortcutService`.`ngOnDestroy()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `KeyboardShortcutService`.`ngOnDestroy()` participates in the `KeyboardShortcutService` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `KeyboardShortcutService`.`ngOnDestroy()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `KeyboardShortcutService`.`ngOnDestroy()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `KeyboardShortcutService`.`ngOnDestroy()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 */


public ngOnDestroy(): void {
    window.removeEventListener('keydown', this.handleKeydown, true);
    if (!this.destroy$.closed) {
      this.destroy$.complete();
      this.destroy$.unsubscribe();
    }
  }

  // ——————————————————————————— private ———————————————————————————

  // Using an arrow function assigned to a property preserves `this` context
  private readonly handleKeydown = (ev: KeyboardEvent): void => {

    if(!this.fmt) {
      console.error('FormattingService is not available in KeyboardShortcutService.');
      return;
    }

    const targetElement = ev.target as HTMLElement | null;

    // IMPORTANT: Only process shortcuts if the event target is inside this specific editor instance.
    // This prevents multiple editor instances from all reacting to the same global keydown event.
    if (!targetElement || !this.editorElement || !this.editorElement.contains(targetElement)) {
      return;
    }

    // Ignore shortcuts if typing inside an input, textarea etc., unless specifically allowed
    // Note: inputs usually have isContentEditable=false. The editor div has isContentEditable=true.
    if (!targetElement.isContentEditable && ['INPUT', 'TEXTAREA', 'SELECT'].includes(targetElement.tagName)) {
      return;
    }

    const match = SHORTCUTS.find(d =>
      ev.key.toLowerCase() === d.key &&
      (d.ctrl  ?? false) === ev.ctrlKey  &&
      (d.meta  ?? false) === ev.metaKey &&
      (d.shift ?? false) === ev.shiftKey &&
      (d.alt   ?? false) === ev.altKey
    );


    if (!match) {
      // No matching shortcut found in our map
      return;
    }

    // Keep native browser history handling for contenteditable editors.
    if (match.action === ShortcutAction.Undo || match.action === ShortcutAction.Redo) {
      return;
    }

    // Prevent default browser action for the matched shortcut (e.g., Ctrl+B making text bold natively)
    ev.preventDefault();
    // Stop the event from bubbling up or triggering other listeners
    ev.stopImmediatePropagation();

    // Call the corresponding service method based on the matched action
    switch (match.action) {
      // Basic Formatting
      case ShortcutAction.Bold:            this.fmt.toggleBold();            break;
      case ShortcutAction.Italic:          this.fmt.toggleItalic();          break;
      case ShortcutAction.Underline:       this.fmt.toggleUnderline();       break;
      case ShortcutAction.Strikethrough:   this.fmt.toggleStrikethrough();   break; // Assumes fmt service has this
      case ShortcutAction.Superscript:     this.fmt.toggleSuperscript();     break; // Assumes fmt service has this (e.g., wrapSelectionWithTag('sup'))
      case ShortcutAction.Subscript:       this.fmt.toggleSubscript();       break; // Assumes fmt service has this (e.g., wrapSelectionWithTag('sub'))
      case ShortcutAction.ClearFormatting: this.fmt.clearFormatting();       break; // Assumes fmt service has this

      // List Formatting
      case ShortcutAction.OrderedList:     this.fmt.toggleList('ordered');   break; // Assumes fmt service has this
      case ShortcutAction.UnorderedList:   this.fmt.toggleList('unordered'); break; // Assumes fmt service has this
      case ShortcutAction.Indent:          this.fmt.indent();                break; // Assumes fmt service has this
      case ShortcutAction.Outdent:         this.fmt.outdent();               break; // Assumes fmt service has this

      // Block Formatting Examples
      case ShortcutAction.Blockquote:      this.fmt.blockquote(); break; // Assumes fmt service has formatBlock
      case ShortcutAction.CodeBlock:       this.fmt.codeBlock();        break; // Assumes fmt service has formatBlock (using <pre> for code)

      // Default case for actions defined in enum but not handled here yet
      default:
        console.warn(`Shortcut action "${match.action}" triggered but not handled in KeyboardShortcutService.`);
    }
  };
}
