import {
  ChangeDetectorRef,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  EventEmitter,
  Input,
  Output,
  ViewChild
} from '@angular/core';
import { ToolbarComponent } from './components/toolbar/toolbar.component';
import { EditorComponent } from "./components/editor/editor.component";
import { ContentService } from "./services/content.service";
import { ImageModalComponent } from "./components/image-modal/image-modal.component";
import { NgIf } from "@angular/common";
import { ImageModalComponentModel } from "./models/image-modal-component-model";
import { ImageService } from "./services/image.service";
import { FormattingService } from "./services/formatting.service";
import { ClickOutsideDirective } from "./directives/click-outside.directive";

/**
 * @generatedInfoDoc
 * InfoDoc: class `LibMagnetarQuillComponent` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `LibMagnetarQuillComponent` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `LibMagnetarQuillComponent` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `LibMagnetarQuillComponent` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 14: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 15: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 16: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 17: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 18: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 19: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 20: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 21: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 22: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 23: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 24: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 25: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 26: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 27: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 28: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 29: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 30: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 31: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 32: class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 33: class `LibMagnetarQuillComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 34: class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 35: class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 */
@Component({
    selector: 'magnetar-quill',
    imports: [ToolbarComponent, EditorComponent, ImageModalComponent, NgIf, ClickOutsideDirective],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    standalone: true,
    templateUrl: './lib-magnetar-quill.component.html',
    styleUrl: './lib-magnetar-quill.component.less'
})
export class LibMagnetarQuillComponent {

  /**
   * The data model for the image modal, used for updating image properties.
   * @public
   */
  public updateModel: ImageModalComponentModel = new ImageModalComponentModel();

  /**
   * A flag to control the visibility of the image editing modal.
   * @public
   */
  public showImageModal: boolean = false;

  /**
   * A flag to control the visibility of the HTML source view.
   * @public
   */
  public isHtmlView: boolean = false;

  /**
   * A reference to the image modal component instance.
   * @private
   */
  @ViewChild('imageModelComponent')
  private imageModalRef!: ImageModalComponent;

  /**
   * The internal data model for the image modal component.
   * @private
   */
  private _imageModalComponentModel!: ImageModalComponentModel;

  /**
   * The public getter for the image modal component model.
   * @returns {ImageModalComponentModel} The current image modal data.
   * @public
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: getter `LibMagnetarQuillComponent`.`imageModalComponentModel` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public get imageModalComponentModel(): ImageModalComponentModel {
    return this._imageModalComponentModel;
  }

  /**
   * The public setter for the image modal component model.
   * When a value is set, it updates the model and triggers change detection.
   * @param {ImageModalComponentModel} value - The new image modal data.
   * @public
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: setter `LibMagnetarQuillComponent`.`imageModalComponentModel` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public set imageModalComponentModel(value: ImageModalComponentModel) {
    if (value) {
      this._imageModalComponentModel = value;
      this.updateModel = value;
      this.cdRef.detectChanges();
    }
  }

  /**
   * An input property to receive the initial HTML content from the parent component.
   * @param {string} value - The HTML content string.
   * @public
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: setter `LibMagnetarQuillComponent`.`content` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: setter `LibMagnetarQuillComponent`.`content` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: setter `LibMagnetarQuillComponent`.`content` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: setter `LibMagnetarQuillComponent`.`content` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: setter `LibMagnetarQuillComponent`.`content` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: setter `LibMagnetarQuillComponent`.`content` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: setter `LibMagnetarQuillComponent`.`content` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
@Input()
  public set content(value: string) {
    this.contentService.setEditorContent(value);
  }

  /**
   * An output event emitter that notifies the parent component of content changes.
   * @public
   */
  @Output()
  public contentChange: EventEmitter<string> = new EventEmitter<string>();

  /**
   * The constructor for the LibMagnetarQuillComponent.
   * @param {ContentService} contentService - The service for managing editor content.
   * @param {FormattingService} formattingService - The service for applying text formatting.
   * @param {ImageService} imageService - The service for handling image-related actions.
   * @param {ChangeDetectorRef} cdRef - The service for manual change detection.
   * @public
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: constructor for class `LibMagnetarQuillComponent` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: constructor for class `LibMagnetarQuillComponent` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: constructor for class `LibMagnetarQuillComponent` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: constructor for class `LibMagnetarQuillComponent` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: constructor for class `LibMagnetarQuillComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: constructor for class `LibMagnetarQuillComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: constructor for class `LibMagnetarQuillComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public constructor(
    private contentService: ContentService,
    private formattingService: FormattingService,
    public imageService: ImageService,
    private cdRef: ChangeDetectorRef
  ) {}

  /**
   * Closes the image editing modal if it is open.
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: method `LibMagnetarQuillComponent`.`closeModal()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `LibMagnetarQuillComponent`.`closeModal()` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `LibMagnetarQuillComponent`.`closeModal()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `LibMagnetarQuillComponent`.`closeModal()` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `LibMagnetarQuillComponent`.`closeModal()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `LibMagnetarQuillComponent`.`closeModal()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `LibMagnetarQuillComponent`.`closeModal()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public closeModal(): void {
    if (this.showImageModal) {
      this.showImageModal = false;
    }
  }

  /**
   * Toggles the visibility of the HTML source view.
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: method `LibMagnetarQuillComponent`.`toggleHtmlView()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `LibMagnetarQuillComponent`.`toggleHtmlView()` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `LibMagnetarQuillComponent`.`toggleHtmlView()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `LibMagnetarQuillComponent`.`toggleHtmlView()` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `LibMagnetarQuillComponent`.`toggleHtmlView()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `LibMagnetarQuillComponent`.`toggleHtmlView()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `LibMagnetarQuillComponent`.`toggleHtmlView()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public toggleHtmlView(): void {
    this.isHtmlView = !this.isHtmlView;
  }

  /**
   * Opens the image editing modal.
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: method `LibMagnetarQuillComponent`.`openImageEditModal()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `LibMagnetarQuillComponent`.`openImageEditModal()` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `LibMagnetarQuillComponent`.`openImageEditModal()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `LibMagnetarQuillComponent`.`openImageEditModal()` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `LibMagnetarQuillComponent`.`openImageEditModal()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `LibMagnetarQuillComponent`.`openImageEditModal()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `LibMagnetarQuillComponent`.`openImageEditModal()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public openImageEditModal(): void {
    this.showImageModal = true;
  }

  /**
   * Hides the image modal after editing is complete.
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: method `LibMagnetarQuillComponent`.`clearImageToEdit()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `LibMagnetarQuillComponent`.`clearImageToEdit()` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `LibMagnetarQuillComponent`.`clearImageToEdit()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `LibMagnetarQuillComponent`.`clearImageToEdit()` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `LibMagnetarQuillComponent`.`clearImageToEdit()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `LibMagnetarQuillComponent`.`clearImageToEdit()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `LibMagnetarQuillComponent`.`clearImageToEdit()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public clearImageToEdit(): void {
    this.showImageModal = false;
  }

  /**
   * Emits the new content to the parent component when the editor content changes.
   * @param {string} newContent - The updated HTML content from the editor.
   */
    /**
   * @generatedInfoDoc
   * InfoDoc: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` is implemented in `projects/lib-magnetar-quill/src/lib/lib-magnetar-quill.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` participates in the `LibMagnetarQuillComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `LibMagnetarQuillComponent`.`onEditorContentChanged()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public onEditorContentChanged(newContent: string): void {
    this.contentChange.emit(newContent);
  }
}
