import {ImageModalComponentModel} from "../models/image-modal-component-model";

/**
 * @generatedInfoDoc
 * InfoDoc: class `ImageHtmlElementImageModalComponentMapper` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `ImageHtmlElementImageModalComponentMapper` is implemented in `projects/lib-magnetar-quill/src/lib/mappers/image-html-element-image-modal-component-mapper.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `ImageHtmlElementImageModalComponentMapper` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `ImageHtmlElementImageModalComponentMapper` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/mappers/image-html-element-image-modal-component-mapper.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `ImageHtmlElementImageModalComponentMapper` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `ImageHtmlElementImageModalComponentMapper` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `ImageHtmlElementImageModalComponentMapper` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `ImageHtmlElementImageModalComponentMapper` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `ImageHtmlElementImageModalComponentMapper` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `ImageHtmlElementImageModalComponentMapper` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `ImageHtmlElementImageModalComponentMapper` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: class `ImageHtmlElementImageModalComponentMapper` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: class `ImageHtmlElementImageModalComponentMapper` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: class `ImageHtmlElementImageModalComponentMapper` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: class `ImageHtmlElementImageModalComponentMapper` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: class `ImageHtmlElementImageModalComponentMapper` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 14: class `ImageHtmlElementImageModalComponentMapper` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 15: class `ImageHtmlElementImageModalComponentMapper` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 16: class `ImageHtmlElementImageModalComponentMapper` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 17: class `ImageHtmlElementImageModalComponentMapper` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 18: class `ImageHtmlElementImageModalComponentMapper` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 19: class `ImageHtmlElementImageModalComponentMapper` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 20: class `ImageHtmlElementImageModalComponentMapper` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 21: class `ImageHtmlElementImageModalComponentMapper` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 */
export class ImageHtmlElementImageModalComponentMapper {

    /**
 * @generatedInfoDoc
 * InfoDoc: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` is implemented in `projects/lib-magnetar-quill/src/lib/mappers/image-html-element-image-modal-component-mapper.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` participates in the `ImageHtmlElementImageModalComponentMapper` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: method `ImageHtmlElementImageModalComponentMapper`.`mapImageModalComponentToImageHtmlElement()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 */
public mapImageModalComponentToImageHtmlElement(imageModalComponentModel: ImageModalComponentModel): HTMLImageElement {

    // Create the image element
    const imageElement: HTMLImageElement = document.createElement('img');

    imageElement.src = imageModalComponentModel.url;
    imageElement.alt = imageModalComponentModel.alt || '';
    imageElement.style.width = imageModalComponentModel.width ? `${imageModalComponentModel.width}px` : 'auto';
    imageElement.style.height = imageModalComponentModel.height ? `${imageModalComponentModel.height}px` : 'auto';
    imageElement.style.borderWidth = `${imageModalComponentModel.border || 0}px`;
    imageElement.style.padding = `${imageModalComponentModel.vPadding || 0}px ${imageModalComponentModel.hPadding || 0}px`;
    imageElement.style.textAlign = imageModalComponentModel.alignment || 'left';

    return imageElement;
  }

    /**
 * @generatedInfoDoc
 * InfoDoc: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` is implemented in `projects/lib-magnetar-quill/src/lib/mappers/image-html-element-image-modal-component-mapper.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` participates in the `ImageHtmlElementImageModalComponentMapper` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: method `ImageHtmlElementImageModalComponentMapper`.`mapImageHtmlElementToImageModalComponent()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 */
public mapImageHtmlElementToImageModalComponent(imageElement: HTMLImageElement): ImageModalComponentModel {
    // Create a new ImageModalComponentModel object
    const imageModalComponentModel = new ImageModalComponentModel();

    // Map properties from the image element to the model
    imageModalComponentModel.url = imageElement.src;
    imageModalComponentModel.alt = imageElement.alt || '';
    imageModalComponentModel.width = imageElement.width || null;
    imageModalComponentModel.height = imageElement.height || null;
    imageModalComponentModel.border = parseInt(imageElement.style.borderWidth || '0', 10);
    imageModalComponentModel.hPadding = parseInt(imageElement.style.paddingLeft || '0', 10);
    imageModalComponentModel.vPadding = parseInt(imageElement.style.paddingTop || '0', 10);

    // Ensure alignment is valid before assigning
    imageElement.style.textAlign = imageModalComponentModel.alignment || 'left';

    return imageModalComponentModel;
  }

}
