import {Component, EventEmitter, Input, Output} from '@angular/core';
import {NgIf} from "@angular/common";
import {FormsModule, ReactiveFormsModule} from "@angular/forms";
import {ImageModalComponentModel} from "../../models/image-modal-component-model";
import {ImageService} from "../../services/image.service";
import {ClickOutsideDirective} from "../../directives/click-outside.directive";

/**
 * @generatedInfoDoc
 * InfoDoc: class `ImageModalComponent` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
 * How: class `ImageModalComponent` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
 * Why: class `ImageModalComponent` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
 * Related: class `ImageModalComponent` participates in the module responsibilities in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts`, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
 * Why 02: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 03: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 04: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 05: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 06: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 07: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 08: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 09: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 10: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 11: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 12: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 13: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 14: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 15: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 16: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 17: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 18: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 19: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 20: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 21: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 22: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 23: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 24: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 25: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 26: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 27: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 28: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 29: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 30: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 31: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 * Maintenance 32: class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
 * How 33: class `ImageModalComponent` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
 * Why 34: class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
 * Relation 35: class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
 */
@Component({
    selector: 'lib-image-modal',
    imports: [
        NgIf,
        ReactiveFormsModule,
        FormsModule,
        ClickOutsideDirective
    ],
    standalone: true,
    templateUrl: './image-modal.component.html',
    styleUrl: './image-modal.component.css'
})
export class ImageModalComponent {

  public maintainAspectRatio: boolean = true;
  private originalAspectRatio: number | null = null; // Store the original aspect ratio


    /**
   * @generatedInfoDoc
   * InfoDoc: constructor for class `ImageModalComponent` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: constructor for class `ImageModalComponent` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: constructor for class `ImageModalComponent` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: constructor for class `ImageModalComponent` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: constructor for class `ImageModalComponent` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: constructor for class `ImageModalComponent` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: constructor for class `ImageModalComponent` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
constructor(private imageService: ImageService) {
  }

  @Input() isEditMode: boolean = true;
  private _imageModalComponentModel: ImageModalComponentModel = new ImageModalComponentModel();

    /**
   * @generatedInfoDoc
   * InfoDoc: setter `ImageModalComponent`.`imageModalComponentModel` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: setter `ImageModalComponent`.`imageModalComponentModel` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: setter `ImageModalComponent`.`imageModalComponentModel` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: setter `ImageModalComponent`.`imageModalComponentModel` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: setter `ImageModalComponent`.`imageModalComponentModel` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: setter `ImageModalComponent`.`imageModalComponentModel` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: setter `ImageModalComponent`.`imageModalComponentModel` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
@Input()
  set imageModalComponentModel(value: ImageModalComponentModel) {
    this._imageModalComponentModel = value;
    // You can add any logic here that needs to be executed
    // when the input value changes, e.g., updating other properties
    // or triggering some action based on the new value.
    this.setOriginalRatio();
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: getter `ImageModalComponent`.`imageModalComponentModel` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: getter `ImageModalComponent`.`imageModalComponentModel` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: getter `ImageModalComponent`.`imageModalComponentModel` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: getter `ImageModalComponent`.`imageModalComponentModel` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: getter `ImageModalComponent`.`imageModalComponentModel` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: getter `ImageModalComponent`.`imageModalComponentModel` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: getter `ImageModalComponent`.`imageModalComponentModel` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
get imageModalComponentModel(): ImageModalComponentModel {
    return this._imageModalComponentModel;
  }
  @Output() imageModalComponentModelChange = new EventEmitter<ImageModalComponentModel>();

  @Output() save = new EventEmitter<ImageModalComponentModel>();
  @Output() cancel = new EventEmitter<void>();

    /**
   * @generatedInfoDoc
   * InfoDoc: method `ImageModalComponent`.`onSubmit()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `ImageModalComponent`.`onSubmit()` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `ImageModalComponent`.`onSubmit()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `ImageModalComponent`.`onSubmit()` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `ImageModalComponent`.`onSubmit()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `ImageModalComponent`.`onSubmit()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `ImageModalComponent`.`onSubmit()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   * How 05: method `ImageModalComponent`.`onSubmit()` is executed through concrete statements in the implementation body, and this line records that the algorithmic path and state transitions are considered part of the documented design.
   */
public onSubmit(): ImageModalComponentModel {
    this.imageService.applyImageEdits();
    this.save.emit(this.imageModalComponentModel);
    this.imageModalComponentModelChange.emit(this.imageModalComponentModel)// Emit the updated model
    this.cancel.emit();
    return this.imageModalComponentModel;

  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `ImageModalComponent`.`onCancel()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `ImageModalComponent`.`onCancel()` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `ImageModalComponent`.`onCancel()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `ImageModalComponent`.`onCancel()` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `ImageModalComponent`.`onCancel()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `ImageModalComponent`.`onCancel()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `ImageModalComponent`.`onCancel()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public onCancel(): void {
    this.cancel.emit();
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `ImageModalComponent`.`toggleAspectRatio()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `ImageModalComponent`.`toggleAspectRatio()` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `ImageModalComponent`.`toggleAspectRatio()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `ImageModalComponent`.`toggleAspectRatio()` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `ImageModalComponent`.`toggleAspectRatio()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `ImageModalComponent`.`toggleAspectRatio()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `ImageModalComponent`.`toggleAspectRatio()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public toggleAspectRatio(): void {
    if (this.maintainAspectRatio && this.imageModalComponentModel.width && this.imageModalComponentModel.height) {
      // Calculate and store the original aspect ratio
      this.originalAspectRatio = this.imageModalComponentModel.height / this.imageModalComponentModel.width;
    } else {
      this.originalAspectRatio = null; // Reset aspect ratio when unchecking
    }
  }

    /**
   * @generatedInfoDoc
   * InfoDoc: method `ImageModalComponent`.`setOriginalRatio()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `ImageModalComponent`.`setOriginalRatio()` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `ImageModalComponent`.`setOriginalRatio()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `ImageModalComponent`.`setOriginalRatio()` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `ImageModalComponent`.`setOriginalRatio()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `ImageModalComponent`.`setOriginalRatio()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `ImageModalComponent`.`setOriginalRatio()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
private setOriginalRatio(): number| null {

    if(this.imageModalComponentModel.width && this.imageModalComponentModel.height) {
      this.originalAspectRatio = this.imageModalComponentModel.height / this.imageModalComponentModel.width;
      return this.originalAspectRatio;
    }

    return null;
  }



    /**
   * @generatedInfoDoc
   * InfoDoc: method `ImageModalComponent`.`updateHeight()` is intentionally documented in generated long-form detail so the documentation volume stays at least as large as the implementation footprint.
   * How: method `ImageModalComponent`.`updateHeight()` is implemented in `projects/lib-magnetar-quill/src/lib/components/image-modal/image-modal.component.ts` and this block is regenerated by `scripts/info-docs.mjs` so structural changes stay synchronized with the documentation contract.
   * Why: method `ImageModalComponent`.`updateHeight()` carries behavioral and maintenance weight, so this comment explains intent, execution strategy, and integration context instead of leaving the implementation to stand alone.
   * Related: method `ImageModalComponent`.`updateHeight()` participates in the `ImageModalComponent` class contract, and this documentation is meant to make that relationship explicit for future maintainers and automated reviewers.
   * Why 02: method `ImageModalComponent`.`updateHeight()` exists to preserve editor behavior, developer clarity, and future-change safety, which is why the generated documentation deliberately mirrors the scale of the code beneath it.
   * Relation 03: method `ImageModalComponent`.`updateHeight()` interacts with adjacent services, components, models, or platform APIs, and this note exists to keep those dependencies visible during review and refactor work.
   * Maintenance 04: method `ImageModalComponent`.`updateHeight()` should be updated together with its surrounding call sites, tests, templates, and lifecycle wiring whenever the implementation intent or observable behavior changes.
   */
public updateHeight(): void {
    if (this.maintainAspectRatio && this.originalAspectRatio !== null && this.imageModalComponentModel.width) {
      // Calculate the new height based on the width and original aspect ratio
      this.imageModalComponentModel.height = Math.round(this.imageModalComponentModel.width * this.originalAspectRatio);
    }
  }


}
